### ISSUE TITLE
231120 오후 회의

### ISSUE THREAD

**Issue by tjkpolisher** [DJMLteam2/DP_main#28]
![20231120_164451](https://github.com/DJMLteam2/DP_main/assets/80250150/a7be307f-246b-4fff-95e2-4cd325ce1a8a)
# What's Done
* 배포를 제외한 기본 과제 모두 수행 완료
    * 구글 맵 API 기본 연동
    * 토글 키 구현 및 연동
    * 기본 ML 모델 연동 및 구동 
    * JSON 파싱(parsing)
* CSS 등 프론트엔드 단의 optional 과제들은 아직 수행하지 않음.
# To-do list
* 지도: 위도/경도 등 좌표 데이터가 들어오면 해당 위치에 점을 찍어주는 기능 필요 → 오픈소스 발견, 적용을 위해 연구 필요

# Issues
- [x] fly.io 배포: 스프링 부트 도커 컨테이너 하나를 fly.io로 배포하면, FastAPI는 어디에?

**Comment by tjkpolisher** [comment]
@8trider 본 이슈에도 강사님 답변 코멘트로 달아주시기 바랍니다.

**Comment by tjkpolisher** [comment]
미리 올려둔 오후회의 이슈가 있어 본 이슈는 닫습니다.

**Comment by 8trider** [comment]
springboot 와 fast-api를 같이 배포 해야 하나 따로 배포 해야 하나?

강사님의 답변 : 따로 배포 해야 한다. 그리고 fly.io로 스프링부트를 배포하긴 버거울 것이다. 즉 둘 다 아마존으로 배포 하는 게 좋다.
